# Generated by Django 4.1.7 on 2023-05-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='peoduct_image/default.png', upload_to='peoduct_image/'),
        ),
    ]
